name: kuryen_tech_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  firebase_storage: ^13.0.2
  image_picker: ^1.2.0
  uuid: ^4.5.1
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  pinput: ^5.0.2
  geolocator: ^14.0.2
  path_provider: ^2.1.5
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
